Changes to make this test work: - Declared items to eliminate the 'error TS2693:  only refers to a type, but is being used as a value here.' error - Imported the Mat* modules - Imported the CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA modules